common:
  para: common1
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    poolName: myPool
    hikari:
      maximum-pool-size: 5

  jpa:
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#    driverClassName: org.postgresql.Driver
#    jdbcUrl: jdbc:postgresql://ruianva.cn:5432/postgres
#    username: postgres
#    password: ruianVA123

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main #重启目录
      exclude: WEB-INF/**
  profiles:
    active: pro
